---
version: "1.0"
services:
  web:
    image: xnct/catstagram:1.0
    expose:
      - port: 80
        as: 80
        accept:
          - catstagram.nijatoes.com
        to:
          - global: true
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 100
deployment:
  web:
    dcloud:
      profile: web
      count: 1
